In [1]:
print('Hi')

Hi


In [2]:
!pip install numpy

In [ ]:
import numpy as np
## Create arrays using numpy
#crearte a 1D array
arr1 = np.array([1,2,3,4,5])
print(arr1)

[1 2 3 4 5]


In [4]:
print(type(arr1))

<class 'numpy.ndarray'>


In [5]:
print(arr1.shape)

(5,)


In [ ]:
#Convert to 2D dimensional array
arr2 = np.array([1,2,3,4,5])
#(1,5) 1 row and 5 columns
arr2.reshape(1,5)

array([[1, 2, 3, 4, 5]])

In [8]:
arr3 = np.array([[1,2,3,4,5]])
print(arr3.shape)

(1, 5)


In [11]:
arr3 = np.array([[1,2,3,4,5],[1,3,4,5,6]])
print(arr3)
print(arr3.shape)

[[1 2 3 4 5]
 [1 3 4 5 6]]
(2, 5)


In [13]:
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [14]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [15]:
#Identical matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [17]:
#Attribute of numpy array
arr = np.array([[1,2,3],[4,5,6]])
print("Array:\n",arr)
print("Shape:",arr.shape)
print("Number of dimentions:",arr.ndim)
print("Size (number of elements):",arr.size)
print("Data type:",arr.dtype)
print("Item size (in bytes):",arr.itemsize)

Array:
 [[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Number of dimentions: 2
Size (number of elements): 6
Data type: int64
Item size (in bytes): 8


In [21]:
### Numpy vectorized operation
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([10,20,30,40,50])
# Eliment wise operation
print("Addition: ",arr1+arr2)
#Element wise subtraction
print("Subtraction ",arr1-arr2)
print("Multiplication",arr1*arr2)
print("Division",arr1/arr2)

Addition:  [11 22 33 44 55]
Subtraction  [ -9 -18 -27 -36 -45]
Multiplication [ 10  40  90 160 250]
Division [0.1 0.1 0.1 0.1 0.1]


In [23]:
#Universal function
arr = np.array([2,3,4,5,6])
#Square root 
print(np.sqrt(arr))
print(np.exp(arr))
print(np.sin(arr))
print(np.log(arr))
 

[1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
[ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
[0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


In [24]:
#Array slicing and indexing
arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [26]:
print(arr[0][0])

1


In [30]:
arr[1:,2:]

array([[ 7,  8],
       [11, 12]])

In [34]:
arr[0:2,2:]

array([[3, 4],
       [7, 8]])

In [35]:
arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [40]:
arr[1:,1:3]

array([[ 6,  7],
       [10, 11]])

In [41]:
#Modify array elements
arr[0][0] = 100

In [42]:
print(arr)

[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [43]:
#statistical concpet -- normalization
# to have mean 0 and standard devivation 1
data = np.array([1,2,3,4,5])
#Calculate mean and standard deviation
mean = np.mean(data)
std_dev = np.std(data)
normalized_data = (data - mean)/std_dev
print("Normalized data:",normalized_data)




Normalized data: [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [45]:
data = np.array([1,2,3,4,5,6,7,8,9,10])
#Mean
mean = np.mean(data) 
print("Mean:",mean)
#Median
median = np.median(data)
print("Median:",median)
#Standard deviation
std_dev = np.std(data)
print("Standard deviation:",std_dev)
#variance 
variance = np.var(data)
print("Variance:",variance)

Mean: 5.5
Median: 5.5
Standard deviation: 2.8722813232690143
Variance: 8.25


In [51]:
#Logical operation
data = np.array([1,2,3,4,5,6,7,8,9,10])
data > 5


array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [58]:
data_store = data[(data>=5) & (data<=8)]

In [59]:
print(data_store)

[5 6 7 8]
