In [1]:
## check

In [1]:
import numpy as np

arr =np.random.randint(1,21,size=(5,5))

arr

array([[ 6, 15,  7, 20, 12],
       [ 8, 16, 12,  6,  9],
       [17,  5,  2, 15,  5],
       [15, 16, 16, 18,  8],
       [ 5, 18,  3,  9,  8]], dtype=int32)

In [2]:
arr[:,2] = 1
print(arr)

[[ 6 15  1 20 12]
 [ 8 16  1  6  9]
 [17  5  1 15  5]
 [15 16  1 18  8]
 [ 5 18  1  9  8]]


In [3]:
arr2 = np.arange(1,17).reshape(4,4)
arr2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [4]:
np.fill_diagonal(arr2,0)
arr2

array([[ 0,  2,  3,  4],
       [ 5,  0,  7,  8],
       [ 9, 10,  0, 12],
       [13, 14, 15,  0]])

In [5]:
# Create a NumPy array of shape (6, 6) with values from 1 to 36. 
# Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.

arr = np.arange(1,37).reshape(6,6)
arr


array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36]])

In [6]:
arr2 = arr[2:5,1:4]
arr2

array([[14, 15, 16],
       [20, 21, 22],
       [26, 27, 28]])

In [7]:
# Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.
arr = np.random.randint(1,101,size=(5,5))
arr

array([[41, 32,  5, 93, 76],
       [13, 51, 71, 17, 46],
       [97, 60, 40, 73, 13],
       [41, 88, 19, 11, 94],
       [26, 49, 52, 20, 28]], dtype=int32)

In [8]:
# Extract the elements on the border
border_elements = np.concatenate((arr[0, :], arr[-1, :], arr[1:-1, 0], arr[1:-1, -1]))
print("Array")
print(arr)
print("\n Border elements")
print(border_elements)


Array
[[41 32  5 93 76]
 [13 51 71 17 46]
 [97 60 40 73 13]
 [41 88 19 11 94]
 [26 49 52 20 28]]

 Border elements
[41 32  5 93 76 26 49 52 20 28 13 97 41 46 13 94]


In [9]:
# Create two NumPy arrays of shape (3, 4) filled with random integers. 
# Perform element-wise addition, subtraction, multiplication, and division.

arr1 = np.random.randint(1,101,size=(3,4))
arr2 = np.random.randint(1,101,size=(3,4))
print(arr1)
print(arr2)
print('Addition')
print(arr1+arr2)
print('Subtraction')
print(arr1-arr2)
print('Multiplication')
print(arr1*arr2)
print("\nDivision:")
# Using np.divide to avoid division by zero errors
print(np.divide(arr1, arr2))



[[80 25 83 56]
 [61 43 56  2]
 [74  5 57 68]]
[[22 51 66 29]
 [88 30  8 45]
 [29 35 14 50]]
Addition
[[102  76 149  85]
 [149  73  64  47]
 [103  40  71 118]]
Subtraction
[[ 58 -26  17  27]
 [-27  13  48 -43]
 [ 45 -30  43  18]]
Multiplication
[[1760 1275 5478 1624]
 [5368 1290  448   90]
 [2146  175  798 3400]]

Division:
[[3.63636364 0.49019608 1.25757576 1.93103448]
 [0.69318182 1.43333333 7.         0.04444444]
 [2.55172414 0.14285714 4.07142857 1.36      ]]


In [10]:
# Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.
arr = np.arange(1,17).reshape(4,4)
print('Array')
print(arr)
row_sum = np.sum(arr,axis=1)
print('Row sum')
print(row_sum)
print('Column Sum')
col_sum = np.sum(arr,axis=0)
print(col_sum)

Array
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Row sum
[10 26 42 58]
Column Sum
[28 32 36 40]


In [11]:
# Create a NumPy array of shape (5, 5) filled with random integers.
#  Compute the mean, median, standard deviation, and variance of the array.
data = np.random.randint(1,101,size=(5,5))
print('Mean')
mean = np.mean(data)
print(mean)
print('Standard deviation')
std_dev = np.std(data)
print(std_dev)
print('Variance')
variance = np.var(data)
print(variance)

Mean
44.56
Standard deviation
31.512638734323726
Variance
993.0464


In [12]:
# Create a NumPy array of shape (3, 3) with values from 1 to 9. 
# Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).
# Create a 3x3 array with values from 1 to 9
data = np.arange(1, 10).reshape(3, 3)

# Compute the mean and standard deviation
mean = np.mean(data)
std_dev = np.std(data)

# Normalize the array
normalized_data = (data - mean) / std_dev

print("Normalized Data:")
print(normalized_data)


Normalized Data:
[[-1.54919334 -1.161895   -0.77459667]
 [-0.38729833  0.          0.38729833]
 [ 0.77459667  1.161895    1.54919334]]


In [13]:
# Create a NumPy array of shape (3, 3) filled with random integers. 
# Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.
arr = np.random.randint(1,21,size=(3,3))
print(arr)
arr_1d = np.array([1,2,3])
result = arr + arr_1d
print(result)

[[10  1 11]
 [ 1  8 11]
 [15  5 18]]
[[11  3 14]
 [ 2 10 14]
 [16  7 21]]


In [14]:
# Create a NumPy array of shape (4, 4) filled with random integers.
#  Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.
arr = np.random.randint(1,21,size=(4,4))
print(arr)
arr_1d = np.array([1,3,4,5])
result = arr - arr_1d
print(result)

[[ 4  4 14  9]
 [17  9 13  9]
 [18  8  6 11]
 [12 11  4 15]]
[[ 3  1 10  4]
 [16  6  9  4]
 [17  5  2  6]
 [11  8  0 10]]


In [15]:
# Create a NumPy array of shape (3, 3) representing a matrix. 
# Compute its determinant, inverse, and eigenvalues.
matrix = np.random.randint(1,10,size=(3,3))
determinant = np.linalg.det(matrix)
if determinant!=0:
    inverse_matrix = np.linalg.inv(matrix)
else:
    inverse_matrix = None
eigenvalues = np.linalg.eig(matrix)
print('Determinant')
print(determinant)
if inverse_matrix is not None:
    print("\nInverse Matrix:")
    print(inverse_matrix)
else:
    print("\nThe matrix is singular (non-invertible).")
print('Eigenvlaues')
print(eigenvalues)

Determinant
207.99999999999997

Inverse Matrix:
[[-0.26923077  0.15384615  0.11538462]
 [-0.11538462 -0.07692308  0.19230769]
 [ 0.26442308  0.00961538 -0.14903846]]
Eigenvlaues
EigResult(eigenvalues=array([18.26331724+0.j        , -3.13165862+1.25764221j,
       -3.13165862-1.25764221j]), eigenvectors=array([[ 0.498934  +0.j        , -0.17950501-0.3380345j ,
        -0.17950501+0.3380345j ],
       [ 0.54586308+0.j        , -0.68168587+0.j        ,
        -0.68168587-0.j        ],
       [ 0.67312581+0.j        ,  0.59433928+0.18861557j,
         0.59433928-0.18861557j]]))


In [16]:
# Create two NumPy arrays of shape (2, 3) and (3, 2). Perform matrix multiplication on these arrays.
# Create two NumPy arrays with shapes (2, 3) and (3, 2)
arr1 = np.random.randint(1, 10, size=(2, 3))
arr2 = np.random.randint(1, 10, size=(3, 2))
result = np.dot(arr1,arr2)
# Print the arrays and the result
print("Array 1 (Shape 2x3):")
print(arr1)

print("\nArray 2 (Shape 3x2):")
print(arr2)

print("\nMatrix Multiplication Result (Shape 2x2):")
print(result)

Array 1 (Shape 2x3):
[[1 4 6]
 [1 2 8]]

Array 2 (Shape 3x2):
[[3 4]
 [1 2]
 [9 7]]

Matrix Multiplication Result (Shape 2x2):
[[61 54]
 [77 64]]


In [18]:
# Create a NumPy array of shape (3, 3) with values from 1 to 9. 
# Reshape the array to shape (1, 9) and then to shape (9, 1).
arr = np.arange(1,10).reshape(3,3)
print(arr)
arr_1x9 = arr.reshape(1, 9)
print(arr_1x9)
arr_9x1 = arr.reshape(9,1)
print(arr_9x1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3 4 5 6 7 8 9]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


In [23]:
# Create a NumPy array of shape (5, 5) filled with random integers.
#  Flatten the array and then reshape it back to (5, 5).
arr = np.random.randint(1,21,size=(5,5))
print(arr)
flatten_array = arr.flatten()
print('Flatten Array')
print(flatten_array)
convert_shape = flatten_array.reshape(5,5)
print('Convert Shape')
print(convert_shape)

[[ 9  2 20 10 18]
 [ 4 18 11 17 11]
 [ 3  2 10  1 10]
 [15 11  7 11 17]
 [17 20  1 13 11]]
Flatten Array
[ 9  2 20 10 18  4 18 11 17 11  3  2 10  1 10 15 11  7 11 17 17 20  1 13
 11]
Convert Shape
[[ 9  2 20 10 18]
 [ 4 18 11 17 11]
 [ 3  2 10  1 10]
 [15 11  7 11 17]
 [17 20  1 13 11]]


In [25]:
# Create a 5x5 array with random integers between 0 and 99
arr = np.random.randint(0, 100, (5, 5))
print("Original array:\n", arr)

# Use fancy indexing to extract the four corners
corners = arr[[0, 0, -1, -1], [0, -1, 0, -1]]
print("\nCorners of the array:", corners)

Original array:
 [[63 94 45 34 55]
 [ 4 94 17 28  1]
 [68 13 56  2 63]
 [66  3 72 61 60]
 [ 4 60 87 74 39]]

Corners of the array: [63 55  4 39]


In [27]:
# Create a NumPy array of shape (4, 4) filled with random integers. Use boolean indexing to set all elements greater than 10 to 10.

arr = np.random.randint(1,21,size=(4,4))
print(arr)
arr[arr>10]=10
print('Modified array')
print(arr)

[[19  5 16 14]
 [19 11 20  7]
 [12 18  2 15]
 [ 8 17 19 13]]
Modified array
[[10  5 10 10]
 [10 10 10  7]
 [10 10  2 10]
 [ 8 10 10 10]]


In [31]:
# Create a structured array with fields 'name' (string), 'age' (integer), and 'weight' (float). Add some data and sort the array by age.

dtype = [('name','U10'),('age','i4'),('weight','f4')]
data = np.array([
    ('Alice',45,55.5),
    ('Robin',30,85.6),
    ('Kamal',70,12.5)
],dtype)
print("Original array:")
print(data)
sorted_data = np.sort(data,order='age')
print(sorted_data)

Original array:
[('Alice', 45, 55.5) ('Robin', 30, 85.6) ('Kamal', 70, 12.5)]
[('Robin', 30, 85.6) ('Alice', 45, 55.5) ('Kamal', 70, 12.5)]


In [34]:
# Create a structured array with fields 'x' and 'y' (both integers). Add some data and compute the Euclidean distance between each pair of points.
dtype =[('x','i4'),('y','i4')]
data = np.array([
    (10,12),
    (32,23),
    (45,52)
],dtype)
dx = np.diff(data['x'])
dy = np.diff(data['y'])

euclidean_distance = np.sqrt(dx**2+dy**2)
print(euclidean_distance)

[24.59674775 31.78049716]


Points:
 [(10, 12) (32, 23) (45, 52)]

Euclidean distances between consecutive points:
[24.59674775 31.78049716]


In [36]:

# Create a 4x4 array of random integers between 0 and 20
arr = np.random.randint(0, 20, (4, 4))
print("Original array:\n", arr)

# Create a masked array where elements > 10 are masked
masked_arr = np.ma.masked_greater(arr, 10)
print("\nMasked array:\n", masked_arr)

# Compute the sum of the unmasked elements
sum_unmasked = masked_arr.sum()
print("\nSum of unmasked elements:", sum_unmasked)

Original array:
 [[19  8  8  6]
 [ 3 17  4 15]
 [19 15  2  3]
 [13  4 11  9]]

Masked array:
 [[-- 8 8 6]
 [3 -- 4 --]
 [-- -- 2 3]
 [-- 4 -- 9]]

Sum of unmasked elements: 47


In [38]:
# Step 1: Create a 3x3 array of random integers (0–20)
arr = np.random.randint(0, 20, (3, 3))
print("Original array:\n", arr)

# Step 2: Mask the diagonal elements
mask = np.eye(3, dtype=bool)  # True on the diagonal
print(mask)
masked_arr = np.ma.masked_array(arr, mask)
print("\nMasked array:\n", masked_arr)

# Step 3: Compute mean of unmasked elements
mean_unmasked = masked_arr.mean()
print("\nMean of unmasked elements:", mean_unmasked)

# Step 4: Replace masked (diagonal) elements with the mean
arr[mask] = mean_unmasked
print("\nArray after replacing masked elements with mean:\n", arr)

Original array:
 [[ 4  0  9]
 [19 13  8]
 [ 5 12 11]]
[[ True False False]
 [False  True False]
 [False False  True]]

Masked array:
 [[-- 0 9]
 [19 -- 8]
 [5 12 --]]

Mean of unmasked elements: 8.833333333333334

Array after replacing masked elements with mean:
 [[ 8  0  9]
 [19  8  8]
 [ 5 12  8]]
