In [1]:
print('Hi')

Hi


In [6]:
import pandas as pd
import numpy as np
data = np.random.randint(0, 100, size=(6, 4))
print(data)
df = pd.DataFrame(data[:,1:], index=data[:,0],columns=["B","C","D"])
print(df)


[[ 2  9 15 33]
 [16  4 14 84]
 [50 71 49 64]
 [49 82 49 25]
 [55 58 57 51]
 [41 25  0 19]]
     B   C   D
2    9  15  33
16   4  14  84
50  71  49  64
49  82  49  25
55  58  57  51
41  25   0  19


In [9]:
# Create a Pandas DataFrame with columns 'A', 'B', 'C' and index 'X', 'Y', 'Z'. 
# Fill the DataFrame with random integers and access the element at row 'Y' and column 'B'.
df = pd.DataFrame(np.random.randint(1,100,size=(3,3)),columns=["A","B","C"],index=["X","Y","Z"])
print(df)
print("\nElement at row 'Y' and column 'B':", df.loc['Y', 'B'])


    A   B   C
X  62  49  76
Y  61  43  88
Z  92  72  84

Element at row 'Y' and column 'B': 43


In [18]:
# Create a Pandas DataFrame with 3 columns and 5 rows filled with random integers. 
# Add a new column that is the product of the first two columns.
df = pd.DataFrame(np.random.randint(0,10,size=(3,5)))
print(df)
print('First column')
print(df[0])
print('Second Column')
print(df[1])
df_new = df[0]*df[1]
print(df_new)
df[5]= df_new
print('After addition')
print(df)

   0  1  2  3  4
0  4  7  3  6  5
1  4  2  7  7  4
2  7  8  9  2  3
First column
0    4
1    4
2    7
Name: 0, dtype: int32
Second Column
0    7
1    2
2    8
Name: 1, dtype: int32
0    28
1     8
2    56
dtype: int32
After addition
   0  1  2  3  4   5
0  4  7  3  6  5  28
1  4  2  7  7  4   8
2  7  8  9  2  3  56


In [22]:
# Create a Pandas DataFrame with 3 columns and 4 rows filled with random integers.
#  Compute the row-wise and column-wise sum.
df = pd.DataFrame(np.random.randint(1, 10, size=(4, 3)), columns=['A', 'B', 'C'])
print('Orginal Df')
print(df)

col_sum = df.sum()
print('Column Sum')
print(col_sum)

row_sum = df.sum(axis=1)
print('Row Sum')
print(row_sum)


Orginal Df
   A  B  C
0  6  8  6
1  3  1  5
2  1  1  3
3  4  9  4
Column Sum
A    14
B    19
C    18
dtype: int64
Row Sum
0    20
1     9
2     5
3    17
dtype: int64


In [32]:
# Create a Pandas DataFrame with 3 columns and 5 rows filled with random integers.
#  Introduce some NaN values. Fill the NaN values with the mean of the respective columns.

df = pd.DataFrame(np.random.randint(1,10,size=(5,3)),columns=["A","B","C"])
# print(np.random.choice(['A','B','C']))
for _ in range(3):
    row = np.random.randint(0,5)
    col = np.random.choice(["A","B","C"])
    df.loc[row,col] = np.nan
print('Df with null values')
print(df)
df_filled = df.fillna(df.mean())
print("\nDataFrame after filling NaN with column means:")
print(df_filled)

# Show column means for verification
print("\nColumn means used for filling:")
print(df.mean())

Df with null values
   A    B    C
0  8  3.0  8.0
1  6  7.0  7.0
2  5  NaN  4.0
3  3  4.0  NaN
4  4  5.0  NaN

DataFrame after filling NaN with column means:
   A     B         C
0  8  3.00  8.000000
1  6  7.00  7.000000
2  5  4.75  4.000000
3  3  4.00  6.333333
4  4  5.00  6.333333

Column means used for filling:
A    5.200000
B    4.750000
C    6.333333
dtype: float64


In [ ]:
# Create a Pandas DataFrame with a datetime index ranging from '2021-01-01' to '2021-12-31'
#  and one column filled with random integers.
#  Compute the rolling mean with a window of 7 days.
dates = pd.date_range('2021-01-01','2021-12-31')
print(dates)
df = pd.DataFrame(len(dates),3)


DatetimeIndex(['2021-01-01', '2021-01-02', '2021-01-03', '2021-01-04',
               '2021-01-05', '2021-01-06', '2021-01-07', '2021-01-08',
               '2021-01-09', '2021-01-10',
               ...
               '2021-12-22', '2021-12-23', '2021-12-24', '2021-12-25',
               '2021-12-26', '2021-12-27', '2021-12-28', '2021-12-29',
               '2021-12-30', '2021-12-31'],
              dtype='datetime64[ns]', length=365, freq='D')
